image: Visual Studio 2017
environment:
  matrix:
    - CMAKE_GENERATOR: Visual Studio 15 2017 Win64
      VS_COMPILER_VERSION: 15
      VCVARS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      ARCHITECTURE: x86_64

shallow_clone: true

install:
    - echo %APPVEYOR_BUILD_FOLDER%
    - mkdir C:\projects\deps
    - cd C:\projects\deps
    - appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip -FileName ninja.zip
    - 7z x ninja.zip -oC:\projects\deps\ninja > nul
    - set PATH=C:\projects\deps\ninja;%PATH%
    - ninja --version

before_build:
    - cmd: cd %APPVEYOR_BUILD_FOLDER%
    - cmd: if not exist envs mkdir envs
    - cmd: cd envs
    - cmd: python -m virtualenv conan
    - cmd: conan/Scripts/activate
    - cmd: python -m pip install conan==1.9.0
    - cmd: cd ..
    - cmd: conan --version
    - cmd: conan remote add conan-bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    - cmd: conan remote list
    - cmd: conan config set storage.path=c:\Users\appveyor\conanCache
    - cmd: conan profile new --detect default
    - cmd: conan profile update settings.compiler.version=%VS_COMPILER_VERSION% default
    - cmd: conan profile update settings.arch=%ARCHITECTURE% default
    - cmd: conan profile update settings.arch_build=%ARCHITECTURE% default
    - cmd: cat c:\Users\appveyor\.conan\conan.conf

build_script:
    - cmd: md build
    - cmd: cd build
    - cmd: call "%VCVARS%" x86_amd64
    - cmd: conan install .. --build missing
    - cmd: echo %CMAKE_GENERATOR%
    - cmd: cmake -GNinja -DEXIV2_TEAM_WARNINGS_AS_ERRORS=ON -DCMAKE_BUILD_TYPE=Release -DEXIV2_ENABLE_NLS=OFF -DEXIV2_ENABLE_PNG=ON -DEXIV2_ENABLE_WEBREADY=OFF -DEXIV2_BUILD_UNIT_TESTS=ON -DCMAKE_INSTALL_PREFIX=install ..
    - cmd: ninja
    - cmd: ninja install
      #- cmd: cmake --build . --config Release
      #- cmd: cmake --build . --config Release --target install
    - cmd: cd bin
    - cmd: unit_tests.exe
    - cmd: cd ../../tests/
    - cmd: set EXIV2_EXT=.exe
    - cmd: c:\Python36\python.exe runner.py -v

cache:
    - envs                          # Conan installation
    - c:\Users\appveyor\conanCache  # Conan cache
